version: 0.2

artifacts:
  files:
    - lead-score/package.yml
  discard-paths: true

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install aws-sam-cli
      - curl https://sh.rustup.rs -sSf | sh -s -- -y
      - export PATH="${HOME}/.cargo/bin:${PATH}"
      - apt-get install pkg-config libssl-dev -y
      - apt-get install libssl-dev musl-tools -y
      - rustup toolchain install stable-x86_64-unknown-linux-musl
      - rustup target add x86_64-unknown-linux-musl
      - export OPENSSL_INCLUDE_DIR=/usr/include/openssl
  build:
    commands:
      - cargo build --release --target x86_64-unknown-linux-musl
      - cp ./target/x86_64-unknown-linux-musl/release/bootstrap ./bootstrap
      - cargo clean
      - sam package --template-file _infra/sam.yml --s3-bucket $S3_BUCKET --output-template-file package.yml